### ISSUE TITLE
Dead project? Would you mind to give me the http://cpython.readthedocs.io/ name?

### ISSUE THREAD

**Issue by vstinner** [danishabdullah/cpython#1]
Hi,

I wanted to create a documentation on CPython called http://cpython.readthedocs.io/ but it seems like you already created it in 2016. This documentation links to https://github.com/danishabdullah/cpython/ which seems to be an "empty repository".

Are you still using http://cpython.readthedocs.io/ ? If not, I'm interested to get the name. It means that you would have to rename or destroy your "cpython" ReadTheDocs project I guess.

I'm a CPython core developer and I wrote a lot of documentation about CPython:
* How to build Python
* How to contribute
* Buildbots
* Debug a crash
* etc.

You can find my documentation at: http://vstinner.readthedocs.io/

Currently, most page names start with "python_" or "cpython_". So my idea is to create a new site called "cpython" rather than vstinner ;-)

**Comment by vstinner** [comment]
I used https://pythondev.readthedocs.io/ name instead ;-)

**Comment by humitos** [comment]
@vstinner cpython slug can be free now. We started the process for Abandoned project more than a month ago. I mentioned this in the CPython Docs Discord the other day. Ping me there if you want to talk more about this.

**Comment by vstinner** [comment]
I'm fine with https://pythondev.readthedocs.io/ URL ;-)
